'use client';
import { motion } from 'framer-motion';
import { ArrowRight, Check, ChevronDown, Clock3, Instagram, Menu, Play, Sparkles, ShoppingBasket, Star, UtensilsCrossed, X } from 'lucide-react';
import { useState } from 'react';

const fade = { hidden: { opacity: 0, y: 24 }, show: { opacity: 1, y: 0, transition: { duration: .65 } } };
const benefits = [{ icon: ShoppingBasket, title: 'Lista de compras pronta', text: 'Tudo organizado para você comprar apenas o necessário.' }, { icon: UtensilsCrossed, title: 'Receitas que funcionam', text: 'Preparos pensados para a vida real e uma rotina possível.' }, { icon: Clock3, title: 'Menos decisões', text: 'Abra o cardápio e saiba exatamente o que fazer durante a semana.' }];
const faqs = [['Para quem é o Cardápio 7 Dias?', 'Para quem quer organizar as refeições da semana com mais praticidade e menos improviso.'], ['O que recebo na compra?', 'Um cardápio em PDF, lista de compras e receitas relacionadas, elaborados por Rita Magalhães.'], ['Como recebo o material?', 'Após a confirmação da compra, o acesso é liberado pela Eduzz.'], ['Posso imprimir?', 'Sim. O material foi pensado para ser consultado no celular ou impresso.'], ['O que é a assinatura de 30 dias?', 'Durante 30 dias, você recebe um novo cardápio, uma nova lista e novas receitas a cada 7 dias.'], ['Existe algum bônus?', 'Não. Você recebe exatamente os materiais descritos nesta página.'], ['Quem elaborou o conteúdo?', 'Rita Magalhães.'], ['Onde tiro dúvidas sobre a compra?', 'Pelo canal de atendimento indicado no seu acesso da Eduzz.']];

function Logo(){ return <a href="#top" className="logo"><span>✳</span> CLUBE DO<br/><b>CARDÁPIO</b></a> }
function Button({children, secondary=false}:{children:React.ReactNode;secondary?:boolean}){ return <a href="#comprar" className={secondary?'button secondary':'button'}>{children}<ArrowRight size={17}/></a> }
function Nav(){ const [open,setOpen]=useState(false); return <header className="nav"><Logo/><nav className={open?'open':''}><a href="#como-funciona">Como funciona</a><a href="#recebe">O que você recebe</a><a href="#para-quem">É para você?</a><a href="#faq">Dúvidas</a><Button>Quero meu cardápio</Button></nav><button className="menu" onClick={()=>setOpen(!open)} aria-label="Menu">{open?<X/>:<Menu/>}</button></header> }
function Hero(){ return <section className="hero section" id="top"><div className="hero-copy"><motion.p className="eyebrow" initial="hidden" animate="show" variants={fade}>PLANEJAMENTO QUE CABE NA SUA ROTINA</motion.p><motion.h1 initial="hidden" animate="show" transition={{delay:.1}} variants={fade}>Uma semana organizada começa <em>à mesa.</em></motion.h1><motion.p className="lead" initial="hidden" animate="show" transition={{delay:.2}} variants={fade}>Cardápio pronto, lista de compras e receitas para você parar de decidir todos os dias o que vai cozinhar.</motion.p><motion.div className="actions" initial="hidden" animate="show" transition={{delay:.3}} variants={fade}><Button>Quero o Cardápio 7 Dias</Button><a className="text-link" href="#recebe"><span className="play"><Play size={13} fill="currentColor"/></span> Veja como funciona</a></motion.div><div className="hero-note"><Star size={15} fill="currentColor"/> Elaborado por Rita Magalhães</div></div><div className="hero-art"><div className="art-circle"><span>7</span><small>DIAS DE<br/>ORGANIZAÇÃO</small></div><div className="art-card card-one"><span>SEG</span><b>Arroz cremoso<br/>com legumes</b></div><div className="art-card card-two"><span>LISTA PRONTA</span><b>Comprar só o<br/>que importa.</b></div><div className="leaf leaf-a">✦</div><div className="leaf leaf-b">✳</div></div></section> }
function Benefits(){ return <section className="benefits section" id="para-quem"><motion.div className="section-heading" initial="hidden" whileInView="show" viewport={{once:true}} variants={fade}><p className="eyebrow">MENOS PRESSA. MAIS PRESENÇA.</p><h2>Você cuida da comida.<br/><em>A gente cuida do resto.</em></h2></motion.div><div className="benefit-grid">{benefits.map(({icon:Icon,title,text},i)=><motion.article className="benefit" key={title} initial="hidden" whileInView="show" viewport={{once:true}} transition={{delay:i*.12}} variants={fade}><div className="icon"><Icon size={22}/></div><h3>{title}</h3><p>{text}</p></motion.article>)}</div></section> }
function Receive(){ const items=[['01','Cardápio completo','Sete dias de refeições pensadas para combinar sabor, variedade e praticidade.'],['02','Lista de compras','Os ingredientes organizados para você ganhar tempo no mercado.'],['03','Receitas relacionadas','O passo a passo para transformar o planejamento em comida gostosa.']]; return <section className="receive section" id="recebe"><div className="receive-visual"><div className="paper"><div className="paper-top">CLUBE DO CARDÁPIO <span>EDIÇÃO 01</span></div><h3>Uma semana<br/><i>bem cuidada.</i></h3><div className="paper-lines"><span>SEGUNDA — Frango assado e legumes</span><span>TERÇA — Massa fresca ao molho</span><span>QUARTA — Bowl de grãos e folhas</span></div><b>RITA MAGALHÃES</b></div></div><div className="receive-copy"><p className="eyebrow">DENTRO DO SEU PDF</p><h2>O essencial para começar bem.</h2>{items.map(([n,t,d])=><motion.div className="receive-item" key={n} initial="hidden" whileInView="show" viewport={{once:true}} variants={fade}><strong>{n}</strong><div><h3>{t}</h3><p>{d}</p></div></motion.div>)}</div></section> }
function How(){ return <section className="how section" id="como-funciona"><div><p className="eyebrow">SIMPLES ASSIM</p><h2>Mais tempo para o que<br/><em>realmente importa.</em></h2></div><div className="steps">{[['01','Você escolhe','Adquire o Cardápio 7 Dias pela Eduzz.'],['02','Você recebe','Acessa o PDF e a lista de compras.'],['03','Você aproveita','Planeja a semana e cozinha com tranquilidade.']].map(([n,t,d])=><motion.div className="step" key={n} initial="hidden" whileInView="show" viewport={{once:true}} variants={fade}><span>{n}</span><h3>{t}</h3><p>{d}</p></motion.div>)}</div></section> }
function Offer(){ return <section className="offer section" id="comprar"><div className="offer-inner"><div><p className="eyebrow">COMECE PELA SUA PRIMEIRA SEMANA</p><h2>Seu próximo cardápio<br/><em>já está pronto.</em></h2><p className="offer-sub">Uma decisão hoje para uma semana inteira mais leve.</p></div><div className="price-card"><p>CARDÁPIO 7 DIAS</p><div className="price"><small>R$</small> 29<sup>90</sup></div><div className="checks"><span><Check/> Cardápio em PDF</span><span><Check/> Lista de compras</span><span><Check/> Receitas relacionadas</span><span><Check/> Elaborado por Rita Magalhães</span></div><a className="button light" href="#comprar">Comprar pela Eduzz <ArrowRight size={17}/></a><small className="secure">Pagamento seguro pela Eduzz</small></div></div></section> }
function FAQ(){ const [active,setActive]=useState<number|null>(null); return <section className="faq section" id="faq"><div className="faq-title"><p className="eyebrow">AINDA COM DÚVIDAS?</p><h2>Tudo bem.<br/><em>Vamos esclarecer.</em></h2><p>Se não encontrou sua resposta, fale com a gente.</p></div><div className="faq-list">{faqs.map(([q,a],i)=><div className={'faq-row '+(active===i?'active':'')} key={q}><button onClick={()=>setActive(active===i?null:i)}><span>{q}</span><ChevronDown size={18}/></button>{active===i&&<motion.p initial={{opacity:0}} animate={{opacity:1}}>{a}</motion.p>}</div>)}</div></section> }
function Footer(){ return <footer><Logo/><div className="footer-links"><a href="#top">Início</a><a href="#recebe">O que você recebe</a><a href="#faq">Dúvidas</a><a href="https://instagram.com" aria-label="Instagram"><Instagram size={18}/></a></div><p>© 2026 Clube do Cardápio. Feito para semanas mais leves.</p></footer> }
export default function Home(){ return <main><Nav/><Hero/><Benefits/><Receive/><How/><Offer/><FAQ/><Footer/></main> }
